[package]
authors = ["realityone <realityone@me.com>"]
name = "libnetkeeper"
version = "0.1.0"

[dependencies]
linked-hash-map = "0.3.0"
openssl = "0.8.2"
rustc-serialize = "0.3.19"
time = "0.1.35"

[lib]
name = "netkeeper"
