[package]
authors = ["realityone <realityone@me.com>"]
name = "libnetkeeper"
version = "0.1.0"

[features]
dev = ["clippy"]

[dependencies]
linked-hash-map = "0.3.0"
num = "0.1.35"
openssl = "0.8.2"
rustc-serialize = "0.3.19"
time = "0.1.35"
clippy = {version = "0.0.95", optional = true}

[lib]
name = "netkeeper"
