[package]
authors = ["realityone <realityone@me.com>"]
name = "libnetkeeper"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
linked-hash-map = "0.3.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"
time = "0.1.35"

[dependencies.clippy]
optional = true
version = "*"

[features]
dev = ["clippy"]

[lib]
name = "netkeeper"
