[package]
authors = ["realityone <realityone@me.com>"]
name = "libnetkeeper"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
linked-hash-map = "0.3.0"
md4 = "0.4.1"
rand = "0.3.15"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
time = "0.1.36"

[dependencies.clippy]
optional = true
version = "*"

[features]
dev = ["clippy"]

netkeeper = []
singlenet = []
drcom = []
ghca = []
srun3k = []
ipclient = []

[lib]
name = "netkeeper"
